config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'property#summary'
  resources :property do
    resources :rooms, except: :index
    collection do
      get 'summary'
    end
  end
  resources :rooms, only: :index
  resources :contracts
  resources :payments
  get 'get_building_rents', to: 'property#get_building_rents'
  get 'get_rooms', to: 'application#get_rooms'
  get 'get_contracts', to: 'application#get_contracts'
  get 'get_amounts', to: 'application#get_amounts'
  get 'get_copy_contracts', to: 'application#get_copy_contracts'
end

app/models/property.rb
class Property < ApplicationRecord
  # validates :prefecture, presence: true
  # validates :city, presence: true
  # validates :building, presence: true
  # validates :business_entity, presence: true
  # validates :total_units, numericality: true
  # validates :management_company, presence: true, if: :management_company_id?

  belongs_to :user
  belongs_to :management_company, optional: true
  has_many :rooms, dependent: :destroy
  has_many :contracts, dependent: :destroy
  has_many :payments, dependent: :destroy

end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  before_action :find_params, only: [:show, :edit, :update, :destroy]

  def summary
    # 今月収入
    @monthly_income = Payment.joins(:contract, :user)
                              .where(user_id: current_user.id, paid_date: Date.today.all_month, not_paid:'0')
                              .sum('contracts.rent')

    # 契約更新対象
    @renew_contract = Contract.joins(:user)
                              .where(user_id: current_user.id)
                              .where("end_date <= ?", Date.today + 90)
                              .where("end_date >= ?", Date.today)
                              .count

    # 今月未納
    @not_paid = Payment.joins(:user)
                        .where(not_paid:'1',user_id: current_user.id, paid_date: Date.today.all_month)
                        .count

    # 累計未納
    @not_paid_all = Payment.joins(:user)
                            .where(not_paid:'1',user_id: current_user.id)
                            .count

    # 月別稼働状況
    @month = params[:month] ? Date.parse(params[:month]) : Date.today
    @occupant_rooms = Room.joins(:contracts).where(user_id: current_user.id)
                          .where(Contract.arel_table[:end_date].gteq @month.beginning_of_month)
                          .where(Contract.arel_table[:start_date].lteq @month.end_of_month)

    @target_rooms = Room.joins(:property).where(Property.arel_table[:purchase_date].lteq @month.end_of_month)
      gon.occupancy_rate = ((@occupant_rooms.count.to_f / @target_rooms.count.to_f)*100).round(2)

    # 月別家賃
    @month_payments = Payment.joins(:property, :user)
                              .where(user_id: current_user.id, paid_date: @month.all_month, not_paid:'0')
                              .group('building').sum('amounts')

      gon.month_labels = @month_payments.map{|p|p[0]}
      gon.month_data = @month_payments.map{|p|p[1]}

    # 過去1年家賃実績
    target_month = Date.today.beginning_of_month
    last_year = target_month - 1.year

    @payments = Payment.joins(:property, :user)
                      .where(user_id: current_user.id, not_paid:'0')
                      .where(Payment.arel_table[:paid_date].gteq last_year)
                      .order(:paid_date)
                      .group('YEAR(paid_date)').group('MONTH(paid_date)')
                      .sum('amounts')
      gon.all_labels = @payments.map{|p|p[0][0].to_s + "年" + p[0][1].to_s + "月"}
      gon.all_data = @payments.map{|p|p[1]}
  end

  def index
    @property = current_user.property.all.order(:building)
  end

  def show
  end

  def new
    @property_company = PropertyCompany.new
  end

  def create
    @property_company = PropertyCompany.new(property_params)
    if @property_company.valid?
      @property_company.save
      redirect_to property_index_path
    else
      flash.now[:errors] = @property_company.errors.full_messages.join(',').gsub(",","<br>")
      render :new
    end
  end

  def edit
    @property_company = PropertyCompany.new(property: @property)
  end

  def update
    @property_company = PropertyCompany.new(property_params, property: @property)
    if @property_company.valid?
      @property_company.update
      redirect_to @property
    else
      flash.now[:errors] = @property_company.errors.full_messages.join(',').gsub(",","<br>")
      render :edit
    end
  end

  def destroy
    if @property.destroy
      redirect_to property_index_path
    else
      render :show
    end
  end

  def get_building_rents
    target_building = params[:property_id]
    target_month = Date.today.beginning_of_month
    last_year = target_month - 1.year
    if target_building == '0'
      @payments = Payment.joins(:property, :user)
                          .where(user_id: current_user.id, not_paid:'0')
                          .where(Payment.arel_table[:paid_date].gteq last_year)
                          .order(:paid_date)
                          .group('paid_date')
                          .sum('amounts')
    else
      @payments = Payment.joins(:property, :user)
                          .where(user_id: current_user.id, not_paid:'0', property_id: target_building)
                          .where(Payment.arel_table[:paid_date].gteq last_year)
                          .order(:paid_date)
                          .group('paid_date')
                          .sum('amounts')
    end
    gon.all_labels = @payments.map{|p|p[0].strftime("%Y年%m月")}
    gon.all_data = @payments.map{|p|p[1]}
    render json: { labels: gon.all_labels, data: gon.all_data}
  end

  private

  def find_params
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property_company).permit(:postal_code, :prefecture, :city, :address_line, :building, :total_units, :building_year, :purchase_date, :property_type, :business_entity, :land_area, :building_area, :sold, :name, :department, :sales_person, :telephone, :email).merge(user_id: current_user.id, management_company_id: params[:management_company_id], property_id: params[:id])
  end
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/views/property/edit.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5 d-flex justify-content-center'>
  <div class='card shadow px-5 py-3' style='max-width: 800px'>
    <h3 class='mx-auto mt-3'>物件情報登録</h3>
    <% unless flash[:errors].nil? %>
      <div class='alert alert-danger'><%= flash[:errors].html_safe %></div>
    <% end %>
    <%= form_with model:@property_company, url:property_path(management_company_id:@property_company.management_company_id), method: :put, local: true do |f| %>
      <div class='row g-3 py-5'>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>郵便番号</label>
          <div class='col-md-3'>
            <%= f.text_field :postal_code, class:'form-control', placeholder:'例：110-0001' %>
          </div>
          <label class='col-md-2 form-label'>売却済み</label>
          <div class='col-md-2'>
            <%= f.check_box :sold, class:'form-check-input' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>都道府県</label>
          <div class='col-md-3'>
            <%= f.text_field :prefecture, class:'form-control', placeholder:'例：東京都', required: true %>
          </div>
          <label class='col-md-2 form-label'>市・区</label>
          <div class='col-md-3'>
            <%= f.text_field :city, class:'form-control', placeholder:'例：台東区', required: true %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>町名番地</label>
          <div class='col-md-8'>
            <%= f.text_field :address_line, class:'form-control', placeholder:'例：谷中1-2-3' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>物件名称</label>
          <div class='col-md-4'>
            <%= f.text_field :building, class:'form-control', placeholder:'例：谷中パークハイツ', required: true %>
          </div>
          <label class='col-md-2 form-label'>総戸数</label>
          <div class='col-md-2'>
            <%= f.number_field :total_units, class:'form-control', placeholder:'例：6' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>築年月</label>
          <div class='col-md-3'>
            <%= f.date_field :building_year, class:'form-control' %>
          </div>
          <label class='col-md-2 form-label'>購買年月</label>
          <div class='col-md-3'>
            <%= f.date_field :purchase_date, class:'form-control', required: true %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>土地面積(㎡)</label>
          <div class='col-md-3'>
            <%= f.text_field :land_area, class:'form-control', placeholder:'例：146.36' %>
          </div>
          <label class='col-md-2 form-label'>建物面積(㎡)</label>
          <div class='col-md-3'>
            <%= f.text_field :building_area, class:'form-control', placeholder:'例：117.44' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>物件種別</label>
          <div class='col-md-3'>
            <%= f.select :property_type, ["1棟マンション","1棟アパート","1棟商業ビル","戸建賃貸","区分マンション","賃貸併用住宅"], {include_blank: '選択してください'}, {class: 'form-control'} %>
          </div>
          <label class='col-md-2 form-label'>所有者</label>
          <div class='col-md-3'>
            <%= f.select :business_entity, ["法人","個人"], {include_blank: '選択してください'}, {required: true, class: 'form-control'} %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>管理会社</label>
          <div class='col-md-8'>
            <%= f.text_field :name, class:'form-control', placeholder:'例：株式会社エイブル' %>
          </div>
        </div>
        <div class='row mb-4'>        
          <label class='col-md-2 form-label'>部署</label>
          <div class='col-md-3'>
            <%= f.text_field :department, class:'form-control', placeholder:'例：開発部' %>
          </div>
          <label class='col-md-2 form-label'>担当者</label>
          <div class='col-md-3'>
            <%= f.text_field :sales_person, class:'form-control', placeholder:'例：山田' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>連絡先</label>
          <div class='col-md-8'>
            <%= f.text_field :telephone, class:'form-control', placeholder:'例：09012345678' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>メールアドレス</label>
          <div class='col-md-8'>
            <%= f.text_field :email, class:'form-control', placeholder:'例：test@mail.com' %>
          </div>
        </div>
        <div class='row my-3'>
          <%= f.submit "登録" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
          <div class=' mt-3 d-flex justify-content-center'>
            <%=link_to 'もどる', property_index_path, class:'' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/property/index.html.erb
<%= render 'layouts/header' %>

<div class='container'>
  <div class='card shadow row g-3 my-5 p-5'>
    <div class='d-flex'>
      <h4 style="margin-right: 40px;">物件一覧</h4>
      <%=link_to '物件登録', new_property_path, class:'btn btn-primary' %>
    </div>
    <table class='table table-hover mt-3'>
      <thead>
        <tr>
          <th>物件名称</th>
          <th>都道府県</th>
          <th>市・区</th>
          <th>物件種別</th>
          <th>部屋数</th>
        </tr>
      </thead>
      <tbody>
        <% @property.each do |property| %>
          <tr onclick='window.location="/property/<%= property.id %>"' role="link" style="cursor: pointer;">
            <td><%= property.building %></td>
            <td><%= property.prefecture %></td>
            <td><%= property.city %></td>
            <td><%= property.property_type %></td>
            <td><%= property.total_units %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/property/new.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5 d-flex justify-content-center'>
  <div class='card shadow px-5 py-3' style='max-width: 800px'>
    <h3 class='mx-auto mt-3'>物件情報登録</h3>
    <% unless flash[:errors].nil? %>
      <div class='alert alert-danger'><%= flash[:errors].html_safe %></div>
    <% end %>
    <%= form_with model:@property_company, url:property_index_path, local: true do |f| %>
      <div class='row g-3 py-5'>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>郵便番号</label>
          <div class='col-md-3'>
            <%= f.text_field :postal_code, class:'form-control', placeholder:'例：110-0001' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>都道府県</label>
          <div class='col-md-3'>
            <%= f.text_field :prefecture, class:'form-control', placeholder:'例：東京都', required: true %>
          </div>
          <label class='col-md-2 form-label'>市・区</label>
          <div class='col-md-3'>
            <%= f.text_field :city, class:'form-control', placeholder:'例：台東区', required: true %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>町名番地</label>
          <div class='col-md-8'>
            <%= f.text_field :address_line, class:'form-control', placeholder:'例：谷中1-2-3' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>物件名称</label>
          <div class='col-md-4'>
            <%= f.text_field :building, class:'form-control', placeholder:'例：谷中パークハイツ', required: true %>
          </div>
          <label class='col-md-2 form-label'>総戸数</label>
          <div class='col-md-2'>
            <%= f.number_field :total_units, class:'form-control', placeholder:'例：6' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>築年月</label>
          <div class='col-md-3'>
            <%= f.date_field :building_year, class:'form-control' %>
          </div>
          <label class='col-md-2 form-label'>購買年月</label>
          <div class='col-md-3'>
            <%= f.date_field :purchase_date, class:'form-control', required: true %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>土地面積(㎡)</label>
          <div class='col-md-3'>
            <%= f.text_field :land_area, class:'form-control', placeholder:'例：146.36' %>
          </div>
          <label class='col-md-2 form-label'>建物面積(㎡)</label>
          <div class='col-md-3'>
            <%= f.text_field :building_area, class:'form-control', placeholder:'例：117.44' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>物件種別</label>
          <div class='col-md-3'>
            <%= f.select :property_type, ["1棟マンション","1棟アパート","1棟商業ビル","戸建賃貸","区分マンション","賃貸併用住宅"], {include_blank: '選択してください'}, {required: true, class: 'form-control'} %>
          </div>
          <label class='col-md-2 form-label'>所有者</label>
          <div class='col-md-3'>
            <%= f.select :business_entity, ["法人","個人"], {include_blank: '選択してください'}, {required: true, class: 'form-control'} %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>管理会社</label>
          <div class='col-md-8'>
            <%= f.text_field :name, class:'form-control', placeholder:'例：株式会社エイブル' %>
          </div>
        </div>
        <div class='row mb-4'>        
          <label class='col-md-2 form-label'>部署</label>
          <div class='col-md-3'>
            <%= f.text_field :department, class:'form-control', placeholder:'例：開発部' %>
          </div>
          <label class='col-md-2 form-label'>担当者</label>
          <div class='col-md-3'>
            <%= f.text_field :sales_person, class:'form-control', placeholder:'例：山田' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>電話番号</label>
          <div class='col-md-8'>
            <%= f.text_field :telephone, class:'form-control', placeholder:'例：09012345678' %>
          </div>
        </div>
        <div class='row mb-4'>
          <label class='col-md-2 form-label'>メールアドレス</label>
          <div class='col-md-8'>
            <%= f.text_field :email, class:'form-control', placeholder:'例：test@mail.com' %>
          </div>
        </div>
        <div class='row my-3'>
          <%= f.submit "登録" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
          <div class=' mt-3 d-flex justify-content-center'>
            <%=link_to 'もどる', property_index_path, class:'' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/property/show.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5'>
  <div class='d-flex justify-content-around mt-5 address-area'>
    <div class='col-8 py-3'>
      <h3 class=''><%= @property.building %></h3>
      <div class=''>
        住所：〒<%= @property.postal_code %>
        <%= @property.prefecture %>
        <%= @property.city %>
        <%= @property.address_line %>
      </div>
    </div>
    <div class='d-flex align-items-center'>
      <div class=''>
        <%=link_to edit_property_path, class:'mx-3' do %>
          <i class="bi bi-pencil-square" style="font-size: 22px; color: #666;"></i>
        <% end %>
        <%=link_to property_path, method: :delete, data: {confirm: "物件に紐付く部屋および契約情報も全て削除されます。削除しますか？"}, class:'mx-3' do %>
          <i class="bi bi-trash3" style="font-size: 22px; color: #666;"></i>
        <% end %>
        <%=link_to '戻る', property_index_path %>
      </div>
    </div>
  </div>
  <div class='tables d-flex justify-content-around mt-4'>
    <div class='col-5'>
      <h5 class='mt-4 text-center table-title'>物件情報</h5>
      <table class='property-table shadow'>
        <tr>
          <th>総戸数</th>
          <td><%= @property.total_units %>戸</td>
        </tr>
        <tr>
          <th>築年月</th>
          <td><%= @property.building_year.strftime("%Y年%-m月") if @property.building_year.present? %></td>
        </tr>
        <tr>
          <th>購入年月</th>
          <td><%= @property.purchase_date.strftime("%Y年%-m月") %></td>
        </tr>
        <tr>
          <th>土地面積</th>
          <td><%= @property.land_area %>㎡</td>
        </tr>
        <tr>
          <th>建物面積</th>
          <td><%= @property.building_area %>㎡</td>
        </tr>
        <tr>
          <th>物件種別</th>
          <td><%= @property.property_type %></td>
        </tr>
        <tr>
          <th>所有者</th>
          <td><%= @property.business_entity %></td>
        </tr>
      </table>
    </div>
    <div class='col-5'>
      <h5 class='mt-4 text-center table-title'>管理会社情報</h5>
      <table class='company-table shadow'>
        <tr>
          <th>会社名</th>
          <td><%= @property.management_company.name if @property.management_company.present? %></td>
        </tr>
        <tr>
          <th>部署</th>
          <td><%= @property.management_company.department if @property.management_company.present? %></td>
        </tr>
        <tr>
          <th>担当者</th>
          <td><%= @property.management_company.sales_person if @property.management_company.present? %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @property.management_company.telephone if @property.management_company.present? %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @property.management_company.email if @property.management_company.present? %></td>
        </tr>
      </table>
    </div>
  </div>
    <div class='' style="margin-top:100px;">
      <div class='d-flex justify-content-center'>
          <h4 class='table-title' style="margin-right: 40px;">部屋一覧</h4>
          <%=link_to '部屋登録', new_property_room_path(@property.id), class:'btn btn-primary' %>
      </div>
      <table class='table  table-hover mt-3'>
        <thead>
          <tr>
            <th>部屋</th>
            <th>間取り</th>
            <th>広さ</th>
            <th>方角</th>
            <th>契約状況</th>
            <th>入居者</th>
            <th>家賃</th>
            <th>管理費</th>
            <th>契約開始日</th>
            <th>契約終了日</th>
          </tr>
        </thead>
        <tbody>
          <% @property.rooms.each do |room| %>
            <tr onclick='window.location="/property/<%= room.property.id %>/rooms/<%= room.id %>"' role="link" style="cursor: pointer;">
              <td><%= room.name %></td>
              <td><%= room.layout %></td>
              <% unless room.room_size.nil? %>
                <td><%= room.room_size %>㎡</td>
              <% else %>
                <td> </td>
              <% end %>
              <td><%= room.direction %></td>
              <% if room.contracts.exists? && room.contracts.order(start_date: :desc).first.end_date >= Date.today %>
                <td>契約中</td>
                <td><%= room.contracts.order(start_date: :desc).first.contractor %></td>
              <% else %>
                <td style="color:red;">空室</td>
                <td>-</td>
              <% end %>
              <% if room.contracts.exists? %>
                <td><%= room.contracts.order(start_date: :desc).first.rent.to_s(:currency, locale: 'jp') %>
                <td><%= room.contracts.order(start_date: :desc).first.management_cost.to_s(:currency, locale: 'jp') %>
                <td><%= room.contracts.order(start_date: :desc).first.start_date.strftime("%Y年%-m月%-d日") %></td>
                <td><%= room.contracts.order(start_date: :desc).first.end_date.strftime("%Y年%-m月%-d日") %></td>
              <% else %>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/property/summary.html.erb
<%= render 'layouts/header' %>

<div class='container'>
  <div class='row g-3 my-3', style='max-height: 50%'>
    <div class='col-md-6 d-flex flex-wrap mx-3'>
      <div class='col-md-6'>
        <div class='card shadow text-center mx-4 my-5'>
          <div class='card-body'>
            <h5 class='card-title'>今月収入</h5>
            <div class='card-text fw-bold fs-3' style='color:#365596'><%= @monthly_income.to_s(:currency, locale: 'jp') %></div>
          </div>
        </div>
      </div>
      <div class='col-md-6'>
        <div class='card shadow text-center mx-4 my-5'>
          <div class='card-body'>
            <%= link_to contracts_path, style:"text-decoration:none;" do%>
              <h5 class='card-title' style='color:#333333'>契約更新対象</h5>
              <div class='card-text fw-bold fs-3' style='color:#365596'><%= @renew_contract %>件</div>
            <% end %>
          </div>
        </div>
      </div>
      <div class='col-md-6'>
        <div class='card shadow text-center mx-4 my-5'>
          <div class='card-body'>
            <%= link_to payments_path, style:"text-decoration:none;" do%>
              <h5 class='card-title' style='color:#333333'>今月未納</h5>
              <div class='card-text fw-bold fs-3' style='color:#BD1A04;'><%= @not_paid %>件</div>
            <% end %>
          </div>
        </div>
      </div>
      <div class='col-md-6'>
        <div class='card shadow text-center mx-4 my-5'>
          <div class='card-body'>
            <%= link_to payments_path, style:"text-decoration:none;" do%>
              <h5 class='card-title' style='color:#333333'>累計未納</h5>
              <div class='card-text fw-bold fs-3' style='color:#BD1A04;'><%= @not_paid_all %>件</div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class='col vacancy-area mx-3 card shadow'>
      <div>
        <h4 class='text-center bg-light p-2 m-3'>稼働状況</h4>
      </div>
      <div class='d-flex justify-content-center'>
          <h5 class='px-5'>
            <%= link_to summary_property_index_path(month:@month.prev_month) do %>
              <i class="bi bi-chevron-double-left"></i>
            <% end %>
          </h5>
          <h5><%= @month.strftime("%Y年%m月") %></h5>
          <h5 class='px-5'>
            <%= link_to summary_property_index_path(month:@month.next_month) do %>
              <i class="bi bi-chevron-double-right"></i>
            <% end %>
          </h5>
        </div>
      <div class='px-5 py-3 dounut-chart'>
        <canvas id="vacancyChart"></canvas>
        <p class='room-count'><%= @occupant_rooms.count %> / <%= @target_rooms.count%>戸</p>
      </div>
    </div>
  </div>
  <div class='row my-3 px-3 card shadow'>
    <h4 class='text-center bg-light my-3 py-2'>家賃</h4>
    <div class='d-flex my-3'>
      <div class='col-md-6 px-4 mt-3 mx-2 text-center'>
        <div class='d-flex justify-content-center'>
          <h5 class='px-5'>
            <%= link_to summary_property_index_path(month:@month.prev_month) do %>
              <i class="bi bi-chevron-double-left"></i>
            <% end %>
          </h5>
          <h5><%= @month.strftime("%Y年%m月") %></h5>
          <h5 class='px-5'>
            <%= link_to summary_property_index_path(month:@month.next_month) do %>
              <i class="bi bi-chevron-double-right"></i>
            <% end %>
          </h5>
        </div>
        <canvas id="monthChart"></canvas>
      </div>
      <div class='col-md-6 px-4 mt-3 mx-2'>
        <div class='row align-items-center justify-content-between'>
          <div class='col-auto'>
            <h5>年間推移</h5>
          </div>
          <div class='col-auto'>
            <select name='property_id', id ='select_building', class='form-control'>
              <option value='0'>累計</option>
              <% current_user.property.all.each do |property| %>
                <option value=<%= property.id %>><%= property.building %></option> 
              <% end %>
            </select>
          </div>
        </div>
        <canvas id="allChart"></canvas>
      </div>
    </div>
  </div>
  </div>