config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'property#summary'
  resources :property do
    resources :rooms, except: :index
    collection do
      get 'summary'
    end
  end
  resources :rooms, only: :index
  resources :contracts
  resources :payments
  get 'get_building_rents', to: 'property#get_building_rents'
  get 'get_rooms', to: 'application#get_rooms'
  get 'get_contracts', to: 'application#get_contracts'
  get 'get_amounts', to: 'application#get_amounts'
  get 'get_copy_contracts', to: 'application#get_copy_contracts'
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :paid_date, presence: true
  validates :amounts,  numericality: {only_integer: true}

  belongs_to :user
  belongs_to :property
  belongs_to :room
  belongs_to :contract
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :find_params, only: [:show, :edit, :update, :destroy]

  def index
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @building_payments = Payment.joins(:property, :user)
                      .where(user_id: current_user.id, paid_date: @month.all_month)
                      .group('building').sum('amounts')

    @all_payments = Payment.joins(:property, :room, :contract, :user)
              .where(user_id: current_user.id, paid_date: @month.all_month).order(:building).order(:name)

    @not_paid = Payment.where(not_paid: true)
  end

  def new
    @contracts = current_user.contracts.where("end_date >= ?",Date.today)
    @form = Form::PaymentCollection.new
    @month = params[:paid_date] ? Date.parse(params[:paid_date]) : Time.zone.today
  end

  def create
    @contracts = current_user.contracts.where("end_date >= ?",Date.today)
    @form = Form::PaymentCollection.new(payment_collection_params)
    if @form.save
      @month = Payment.last.paid_date
      redirect_to payments_path(month:@month)
    else
      flash.now[:errors] = @form.errors.gsub(",","<br>")
      @form = Form::PaymentCollection.new
      @month = params[:paid_date] ? Date.parse(params[:paid_date]) : Time.zone.today
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @payment.update(payment_params)
      redirect_to payments_path(month:@payment.paid_date)
    else
      flash.now[:errors] = @payment.errors.full_messages.join(',').gsub(",","<br>")
      render :edit
    end
  end

  def destroy
    if @payment.destroy
      redirect_to payments_path(month:@payment.paid_date)
    else
      render payments_path(month:@payment.paid_date)
    end
  end

  private

  def find_params
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:paid_date, :not_paid, :amounts, :property_id, :room_id, :contract_id).merge(user_id: current_user.id)
  end

  def payment_collection_params
    params.require(:form_payment_collection)
    .permit(payments_attributes: [:paid_date, :not_paid, :amounts, :property_id, :room_id, :contract_id, :user_id, :checked])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payments_form.html.erb
<%= form_with(model:@form, url: payments_path, method: :post, local: true) do |f| %>
        <table class="table">
          <thead>
            <tr>
              <th>物件名称</th>
              <th>部屋</th>
              <th>契約開始日</th>
              <th>金額</th>
              <th>支払い月</th>
              <th>未納チェック</th>
            </tr>
          </thead>
          <tbody class="bulk-registration-form">
            <%= f.fields_for :payments do |payment| %>
              <tr class="item", id='payments-form', data-name=<%= payment.index %>>
                <td>
                  <select name='form_payment_collection[payments_attributes][<%= payment.index %>][property_id]', id ='property_id_1', class='form-control' required>
                    <option value='' disabled selected>選択してください</option>
                    <% current_user.property.all.each do |property| %>
                    <option value=<%= property.id %>><%= property.building %></option> 
                    <% end %>
                  </select>
                </td>
                <td>
                  <select name='form_payment_collection[payments_attributes][<%= payment.index %>][room_id]', id ='room-select', class='form-control' required>
                    <option value='' disabled selected>選択してください</option>
                    <% current_user.rooms.all.each do |room| %>
                      <option value=<%= room.id %>><%= room.name %></option> 
                    <% end %>
                  </select>
                </td>
                <td>
                  <select name='form_payment_collection[payments_attributes][<%= payment.index %>][contract_id]', id ='contract-select', class='form-control' required>
                    <option value='' disabled selected>選択してください</option>
                    <% current_user.contracts.all.each do |contract| %>
                      <option value=<%= contract.id %>><%= contract.start_date %></option> 
                    <% end %>
                  </select>
                </td>
                <td>
                  <%= payment.text_field :amounts, class:'form-control', id:'amounts', required: true %>
                </td>
                <td>
                  <%= payment.date_select :paid_date, {discard_day: true, start_year:2000}, class:'form-control' %>
                </td>
                <td>
                  <%= payment.check_box :not_paid %>
                  <%= payment.label :not_paid, "未" %>
                </td>
                <%= payment.hidden_field :user_id, value: current_user.id, id:'room_user_id' %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%# <div class='mx-auto col-md-4 text-center'>
          <%= link_to '入力欄追加', '#', id:'add-form-btn' %>
        </div> %>
        <div class='row my-3'>
          <%= f.submit "登録" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
          <div class=' mt-3 d-flex justify-content-center'>
            <%=link_to 'もどる', payments_path, class:'' %>
          </div>
        </div>
      <% end %>

app/views/payments/edit.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5 d-flex justify-content-center'>
  <div class='card shadow px-5 py-3' style='max-width: 700px'>
    <h3 class='mx-auto mt-3'>支払い情報編集</h3>
    <% unless flash[:errors].nil? %>
      <div class='alert alert-danger'><%= flash[:errors].html_safe %></div>
    <% end %>
    <%= form_with model:@payment, local: true do |f| %>
      <div class='row g-3 py-5'>
        <div class='property-area mb-3 row'>
          <label class='col-md-3 form-label'>物件名称</label>
          <div class='col-md-7'>
            <%= @payment.property.building %>
          </div>
        </div>
        <div class='row mb-3', id="room-area">
          <label class='col-md-3 form-label'>部屋</label>
          <div class='col-md-7'>
            <%= @payment.room.name %>
          </div>
        </div>
        <div class='row mb-3'>
          <label class='col-md-3 form-label'>支払い月</label>
          <div class='col-md-7'>
            <%= @payment.paid_date.strftime("%Y年%m月") %>
          </div>
        </div>
        <div class='row mb-3'>
          <label class='col-md-3 form-label'>家賃</label>
          <div class='col-md-7'>
            <%= @payment.contract.rent.to_s(:currency, locale: 'jp') %>
          </div>
        </div>
        <div class='row mb-3'>
        <%= f.hidden_field :property_id %>
        <%= f.hidden_field :room_id %>
        <%= f.hidden_field :contract_id %>
        <%= f.hidden_field :paid_date %>
        <div class='row mb-3'>
          <label class='col-md-3 form-label'>支払い金額</label>
          <div class='col-md-7'>
            <%= f.text_field :amounts, class:'form-control', id:'amounts', required: true %>
          </div>
        </div>
          <label class='col-md-3 form-label'>未納チェック</label>
          <div class='col-md-7'>
            <%= f.check_box :not_paid %>
            <%= f.label :not_paid, "未" %>
          </div>
        </div>
        <div class='row mb-3'>
          <%= f.submit "更新" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
          <div class=' mt-2 d-flex justify-content-center'>
            <%=link_to 'もどる', payments_path, class:'' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/payments/index.html.erb
<%= render 'layouts/header' %>

<div class='container'>
  <div class='card shadow my-5 py-3 px-5 text-center col-md-6'>
    <h5 class='' style="color:red;">未納</h5>
    <div>
      <table class='table table-hover'>
        <thead>
          <tr>
            <th>支払い月</th>
            <th>物件名称</th>
            <th>部屋</th>
            <th>家賃</th>
          </tr>
        </thead>
        <body>
          <% @not_paid.each do |n| %>
            <tr onclick='window.location="/payments/<%= n.id %>/edit"' role="link" style="cursor: pointer;">
              <td><%= n.paid_date.strftime("%Y年%m月") %></td>
              <td><%= n.property.building %></td>
              <td><%= n.room.name %></td>
              <td><%= n.amounts.to_s(:currency, locale: 'jp') %></td>
            </tr>
          <% end %>
        </body>
      </table>
    </div>
  </div>
  <div class='row card shadow row g-3 my-2 p-5'>
    <div class='d-flex'>
      <h4 style="margin-right: 40px;">支払い状況</h4>
      <%=link_to '支払い登録', new_payment_path(paid_date: @month), class:'btn btn-primary' %>
    </div>
    <div>
      <div class='d-flex justify-content-center'>
        <h4 class='px-5'>
          <%= link_to payments_path(month:@month.prev_month) do %>
            <i class="bi bi-chevron-double-left"></i>
          <% end %>
        </h4>
        <h3><%= @month.strftime("%Y年%m月") %></h3>
        <h4 class='px-5'>
          <%= link_to payments_path(month:@month.next_month) do %>
            <i class="bi bi-chevron-double-right"></i>
          <% end %>
        </h4>
      </div>
      <table class='table'>
        <thead>
          <tr>
            <th>物件名称</th>
            <th>合計家賃</th>
          </tr>
        </thead>
        <tbody>
          <% @building_payments.each do |payment| %>
            <tr>
              <td><%= payment[0] %></td>
              <td><%= payment[1].to_s(:currency, locale: 'jp') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div style="margin-top:100px;">
      <table class='table table-hover'>
        <thead>
          <tr>
            <th>支払い月</th>
            <th>物件名称</th>
            <th>部屋</th>
            <th>家賃</th>
            <th>支払い</th>
          </tr>
        </thead>
        <tbody>
          <% @all_payments.each do |payment| %>
            <tr>
              <td><%= payment.paid_date.strftime("%Y年%m月") %></td>
              <td><%= payment.property.building %></td>
              <td><%= payment.room.name %></td>
              <td><%= payment.amounts.to_s(:currency, locale: 'jp') %></td>
              <% if payment.not_paid %>
                <td style="color:red;">未納</td>
              <% else %>
                <td>○</td>
              <% end %>
              <td>
                <%=link_to edit_payment_path(payment.id), class:'mx-3' do %>
                  <i class="bi bi-pencil-square" style="font-size: 22px; color: #666;"></i>
                <% end %>
                <%=link_to payment_path(payment.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class:'' do %>
                  <i class="bi bi-trash3" style="font-size: 22px; color: #666;"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5'>
  <div class='card shadow px-5 py-3'>
    <h3 class='mx-auto mt-3'>支払い情報登録</h3>
    <% unless flash[:errors].nil? %>
      <div class='alert alert-danger'><%= flash[:errors].html_safe %></div>
    <% end %>
    <%= form_with(model:@form, url: payments_path, method: :post, local: true) do |payments| %>
      <div class='row mt-5'>
        <div class='col-2', style="display: inline-block; width: auto;">
          <%= payments.label :paid_date, '対象月：' %>
        </div>
        <div class='col-2'>
          <%= payments.date_select :paid_date, {discard_day: true, default: @month}, {class: "form-control select_paid_date", style:"display: inline-block; width: auto;"}%>
        </div>
      </div>
      <table class="table mt-3">
        <thead>
          <tr>
            <th>
              <input type='button' id='check_all' value='選択/解除' class=''>
            </th>
            <th>物件名称</th>
            <th>部屋</th>
            <th>金額</th>
            <th>未納チェック</th>
          </tr>
        </thead>
        <tbody>
          <% @contracts.each do |f| %>
            <%= payments.fields_for :payments do |p|%>
              <tr>
                <td><%= p.check_box :checked, class:'check form-check-input' %></td>
                <td><%= p.select :property_id, { f.property.building => f.property_id },{selected: f.property_id},{ class: 'form-control', required: true, readonly: true } %></td>
                <td><%= p.select :room_id, { f.room.name => f.room_id },{selected: f.room_id},{ class: 'form-control', required: true, readonly: true } %></td>
                <td><%= p.text_field :amounts, value: f.rent, class: 'form-control', required: true %></td>
                <td><%= p.check_box :not_paid, { class: 'form-check-input'} %></td>
                <td><%= p.hidden_field :paid_date, value: @month, class:'paid_dates'%></td>
                <%= p.hidden_field :contract_id, value: f.id %>
                <%= p.hidden_field :user_id, value: current_user.id %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class='row my-3'>
        <%= payments.submit "登録" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
        <div class=' mt-3 d-flex justify-content-center'>
          <%=link_to 'もどる', payments_path, class:'' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/payments/show.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5'>
  <h3 class='mb-3'>支払い情報</h3>
  <div class='mb-3'>
    物件名称：<%= @payment.property.building %>
  </div>
  <div class='mb-3'>
    部屋番号：<%= @payment.room.name %>
  </div>
  <div class='mb-3'>
    支払い月：<%= @payment.paid_date.strftime("%Y年%m月") %>
  </div>
  <div class='mb-3'>
    家賃：<%= @payment.contract.rent %>円
  </div>
    <div class='mb-3'>
    未納：<%= @payment.not_paid %>
  </div>
  <div>
    <%=link_to edit_payment_path, class:'mx-3' do %>
      <i class="bi bi-pencil-square" style="font-size: 22px; color: #666;"></i>
    <% end %>
    <%=link_to payment_path, method: :delete, data: {confirm: "削除しますか？"}, class:'' do %>
      <i class="bi bi-trash3" style="font-size: 22px; color: #666;"></i>
    <% end %>
    <%=link_to '戻る', payments_path %>
  </div>
</div>