config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'property#summary'
  resources :property do
    resources :rooms, except: :index
    collection do
      get 'summary'
    end
  end
  resources :rooms, only: :index
  resources :contracts
  resources :payments
  get 'get_building_rents', to: 'property#get_building_rents'
  get 'get_rooms', to: 'application#get_rooms'
  get 'get_contracts', to: 'application#get_contracts'
  get 'get_amounts', to: 'application#get_amounts'
  get 'get_copy_contracts', to: 'application#get_copy_contracts'
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
  validates :room_size, numericality: {greater_than_or_equal_to: 1.00, message: 'は1.00以上の半角数値で入力してください'}, allow_blank: true

  belongs_to :user
  belongs_to :property
  has_many :contracts, dependent: :destroy
  has_many :payments, dependent: :destroy

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_params, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.joins(:property, :user)
                  .where(user_id: current_user.id)
                  .order("properties.building")
                  .order("rooms.name")
  end

  def new
    @property = Property.find(params[:property_id])
    @form = Form::RoomCollection.new
  end

  def create
    @property = Property.find(params[:property_id])
    @form = Form::RoomCollection.new(room_collection_params)
    if @form.save
      redirect_to property_path(@property.id)
    else
      flash.now[:errors] = @form.errors.gsub(",","<br>")
      render :new
    end
  end

  def show
  end

  def edit
    @property = Property.find(params[:property_id])
  end

  def update  
    if @room.update(room_params)
      redirect_to property_path(@room.property.id)
    else
      flash.now[:errors] = @room.errors.full_messages.join(',').gsub(",","<br>")
      @property = Property.find(params[:property_id])
      render :edit
    end
  end

  def destroy
    if @room.destroy
      redirect_to property_path(@room.property.id)
    else
      render :show
    end
  end

  private

  def find_params
    @room = Room.find(params[:id])
  end

  def room_params
    params
    .require(:room)
    .permit(:name, :layout, :room_size, :direction)
    .merge(property_id: params[:property_id], user_id: current_user.id)
  end

  def room_collection_params
    params
      .require(:form_room_collection)
      .permit(rooms_attributes:  [:name, :layout, :room_size, :direction, :property_id, :user_id])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5 d-flex justify-content-center'>
  <div class='card shadow px-5 py-3' style='max-width: 700px'>
    <h3 class='mx-auto mt-3'>部屋情報編集</h3>
      <h5 class='mt-3 mx-auto'><%= @property.building %></h5>
      <% unless flash[:errors].nil? %>
        <div class='alert alert-danger'><%= flash[:errors].html_safe %></div>
      <% end %>
      <%= form_with(model:[@property, @room], local: true) do |f| %>
        <div class='row g-3 py-5'>
          <div class='row mb-3'>
            <label class='col-md-3 form-label'>部屋番号</label>
            <div class='col-md-7'>
              <%= f.text_field :name, class:'form-control', placeholder:'101', required: true %>
            </div>
          </div>
          <div class='row mb-3'>
            <label class='col-md-3 form-label'>間取り</label>
            <div class='col-md-7'>
              <%= f.text_field :layout, class:'form-control', placeholder:'1K' %>
            </div>
          </div>
          <div class='row mb-3'>
            <label class='col-md-3 form-label'>広さ(㎡)</label>
            <div class='col-md-7'>
              <%= f.text_field :room_size, class:'form-control', placeholder:'23.3' %>
            </div>
          </div>
          <div class='row mb-3'>
            <label class='col-md-3 form-label'>方角</label>
            <div class='col-md-7'>
              <%= f.text_field :direction, class:'form-control', placeholder:'南東' %>
            </div>
          </div>
          <div class='row my-3'>
            <%= f.submit "更新" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
            <div class=' mt-3 d-flex justify-content-center'>
              <%=link_to 'もどる', property_room_path(@room.id), class:'' %>
            </div>
          </div>
      <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<%= render 'layouts/header' %>

<div class='container'>
  <div class='card shadow row g-3 my-5 p-5'>
    <div class='text-center'>
      <h4>部屋一覧</h4>
    </div>
    <table class='table table-hover mt-3'>
      <thead>
        <tr>
          <th>物件名称</th>
          <th>部屋</th>
          <th>間取り</th>
          <th>広さ</th>
          <th>方角</th>
          <th>契約状況</th>
          <th>入居者</th>
          <th>家賃</th>
          <th>管理費</th>
          <th>契約開始日</th>
          <th>契約終了日</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr onclick='window.location="/property/<%= room.property.id %>/rooms/<%= room.id %>"' role="link" style="cursor: pointer;">
            <td><%= room.property.building %></td>
            <td><%= room.name %></td>
            <td><%= room.layout %></td>
            <td><%= room.room_size %></td>
            <td><%= room.direction %></td>
            <% if room.contracts.exists? && room.contracts.order(start_date: :desc).first.end_date >= Date.today %>
              <td>契約中</td>
              <td><%= room.contracts.order(start_date: :desc).first.contractor %></td>
            <% else %>
              <td style="color:red;">空室</td>
              <td>-</td>
            <% end %>
            <% if room.contracts.exists? %>
              <td><%= room.contracts.order(start_date: :desc).first.rent.to_s(:currency, locale: 'jp') %>
              <td><%= room.contracts.order(start_date: :desc).first.management_cost.to_s(:currency, locale: 'jp') %>
              <td><%= room.contracts.order(start_date: :desc).first.start_date.strftime("%Y年%-m月%-d日") %></td>
              <td><%= room.contracts.order(start_date: :desc).first.end_date.strftime("%Y年%-m月%-d日") %></td>
            <% else %>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5 d-flex justify-content-center'>
  <div class='card shadow px-5 py-3' style='max-width: 900px'>
    <h3 class='mx-auto mt-3'>部屋情報登録</h3>
      <h5 class='mt-3 mx-auto'><%= @property.building %></h5>
      <% unless flash[:errors].nil? %>
        <div class='alert alert-danger'><%= flash[:errors].html_safe %></div>
      <% end %>      
      <%= form_with(model:@form, url: property_rooms_path, method: :post, local: true) do |f| %>
        <table class="table">
          <thead>
            <tr>
              <th>部屋番号</th>
              <th>間取り</th>
              <th>広さ(㎡)</th>
              <th>方角</th>
            </tr>
          </thead>
          <tbody class="bulk-registration-form">
            <%= f.fields_for :rooms do |room| %>
              <tr class="item", id='rooms-form', data-name=<%= room.index %>>
                <td>
                <%= room.text_field :name, class: 'form-control', placeholder:'例：101', required: true %>
                </td>
                <td>
                <%= room.text_field :layout, class: 'form-control', placeholder:'例：1K' %>
                </td>
                <td>
                <%= room.text_field :room_size, class: 'form-control', placeholder:'例：23.3' %>
                </td>
                <td>
                <%= room.text_field :direction, class: 'form-control', placeholder:'例：南東' %>
                </td>
                <%= room.hidden_field :property_id, value: @property.id, id:'room_property_id' %>
                <%= room.hidden_field :user_id, value: current_user.id, id:'room_user_id' %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class='mx-auto col-md-4 text-center'>
          <%= link_to '入力欄追加', '#', id:'add-form-btn' %>
        </div>
        <div class='row my-4'>
          <%= f.submit "一括登録" ,class:'d-block mx-auto col-md-4 btn btn-primary' %>
          <div class=' mt-3 d-flex justify-content-center'>
            <%=link_to 'もどる', property_path(@property.id), class:'' %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<%= render 'layouts/header' %>

<div class='container mt-5'>
  <h3>部屋情報</h3>
  <div class='mt-3'>
    <h4><%= @room.property.building %></h4>
  </div>
  <div class='d-flex justify-content-between align-items-center'>
    <h5 class=''><%= @room.name %></h5>
    <div class='mx-2 px-2'>
      <%=link_to edit_property_room_path, class:'mx-3' do %>
        <i class="bi bi-pencil-square" style="font-size: 22px; color: #666;"></i>
      <% end %>
      <%=link_to property_room_path, method: :delete, data: {confirm: "部屋に紐付く契約も全て削除されます。削除しますか？"}, class:'mx-3' do %>
        <i class="bi bi-trash3" style="font-size: 22px; color: #666;"></i>
      <% end %>
      <%=link_to '戻る', property_path(@room.property.id) %>
    </div>
  </div>

  <table class='table mt-3'>
    <thead>
      <tr>
        <th>間取り</th>
        <th>広さ</th>
        <th>方角</th>
        <th>契約状況</th>
        <th>入居者</th>
        <th>契約開始日</th>
        <th>契約終了日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @room.layout %></td>
        <% unless @room.room_size.nil? %>
          <td><%= @room.room_size %>㎡</td>
        <% else %>
          <td> </td>
        <% end %>
        <td><%= @room.direction %></td>
        <% if @room.contracts.exists? && @room.contracts.order(start_date: :desc).first.end_date >= Date.today %>
          <td>契約中</td>
          <td><%= @room.contracts.order(start_date: :desc).first.contractor %></td>
        <% else %>
          <td style="color:red;">空室</td>
          <td>-</td>
        <% end %>
        <% if @room.contracts.exists? %>
          <td><%= @room.contracts.order(start_date: :desc).first.start_date.strftime("%Y年%-m月%-d日") %></td>
          <td><%= @room.contracts.order(start_date: :desc).first.end_date.strftime("%Y年%-m月%-d日") %></td>
        <% else %>
          <td>-</td>
          <td>-</td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <div class='mt-5'>
    <div class='d-flex'>
      <h5 style="margin-right: 40px;">契約一覧</h5>
      <%=link_to '契約登録', new_contract_path(property_id: @room.property.id, room_id: @room.id), class:'btn btn-primary' %>
    </div>
    <table class='table mt-3'>
      <thead>
        <tr>
          <th>契約開始日</th>
          <th>契約終了日</th>
          <th>家賃</th>
          <th>契約者</th>
        </tr>
      </thead>
      <tbody>
        <% @room.contracts.order(start_date: :desc).each do |contract| %>
          <tr>
            <td><%= contract.start_date.strftime("%Y年%-m月%-d日") %></td>
            <td><%= contract.end_date.strftime("%Y年%-m月%-d日") %></td>
            <td><%= contract.rent.to_s(:currency, locale: 'jp') %></td>
            <td><%= contract.contractor %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>