config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'property#summary'
  resources :property do
    resources :rooms, except: :index
    collection do
      get 'summary'
    end
  end
  resources :rooms, only: :index
  resources :contracts
  resources :payments
  get 'get_building_rents', to: 'property#get_building_rents'
  get 'get_rooms', to: 'application#get_rooms'
  get 'get_contracts', to: 'application#get_contracts'
  get 'get_amounts', to: 'application#get_amounts'
  get 'get_copy_contracts', to: 'application#get_copy_contracts'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert" style='color:red;'>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-lg navbar-light justify-content-center sticky-top bg-white'>
  <div class='container'>
    <div class='navbar-custom'>
      <%= link_to image_tag('house', size: '40x40'), root_path, class:'navbar-brand' %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class='nav-item px-2'>
          <%= link_to '物件管理', property_index_path, class: 'nav-add' %>
        </li>
        <li class='nav-item px-2'>
          <%= link_to '部屋管理', rooms_path, class: 'nav-add' %>
        </li>
        <li class='nav-item px-2'>
          <%= link_to '家賃管理', payments_path, class: 'nav-add' %>
        </li>
        <li class='nav-item px-2'>
          <%= link_to '契約管理', contracts_path, class: 'nav-add' %>
        </li>
      </ul>
      <div class='nav-item ms-auto d-flex'>
        <div class='mx-5'>
          <%= link_to current_user.nickname, edit_user_registration_path, class:'nav-add' %>
        </div>
        <div class='logout-link'>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'nav-add' %>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class='navbar-add shadow mx-4'>
</div>

app/views/layouts/_select_room.html.erb
<%= label :contract, :room_id %><br>
<%= collection_select :room, :id, Room.where(property_id: property_id), :id, :name, { include_blank: '選択してください'}, {class:'pulldown'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.js" integrity="sha512-uLlukEfSLB7gWRBvzpDnLGvzNUluF19IDEdUoyGAtaO0MVSBsQ+g3qhLRL3GTVoEzKpc24rVT6X1Pr5fmsShBg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('house.ico') %>
    <%= Gon::Base.render_data %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>